# Generated by Django 4.2.3 on 2023-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('num_dep', models.IntegerField(db_column='Num_dep', primary_key=True, serialize=False)),
                ('count_workers', models.IntegerField(blank=True, db_column='Count_workers', null=True)),
            ],
            options={
                'db_table': 'Dep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Cyrillic_General_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Cyrillic_General_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('num_medical', models.IntegerField(db_column='Num_medical', primary_key=True, serialize=False)),
                ('data_start_medical', models.DateField(db_column='Data_start_medical')),
                ('data_end_medical', models.DateField(db_column='Data_end_medical')),
            ],
            options={
                'db_table': 'Medical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('num_mission', models.IntegerField(db_column='Num_mission', primary_key=True, serialize=False)),
                ('place_order', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Place_order', max_length=50, null=True)),
                ('data_start_mission', models.DateField(db_column='Data_start_mission')),
                ('data_end_mission', models.DateField(db_column='Data_end_mission')),
            ],
            options={
                'db_table': 'Mission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('num_order', models.IntegerField(db_column='Num_order', primary_key=True, serialize=False)),
                ('type_order', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Type_order', max_length=15)),
                ('data_order', models.DateField(db_column='Data_order')),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stafflist',
            fields=[
                ('id_record', models.IntegerField(db_column='ID_record', primary_key=True, serialize=False)),
                ('post_name', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Post_name', max_length=50)),
                ('count_units', models.IntegerField(db_column='Count_units')),
                ('salary', models.FloatField(db_column='Salary')),
            ],
            options={
                'db_table': 'StaffList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('num_statement', models.IntegerField(db_column='Num_statement', primary_key=True, serialize=False)),
                ('type_statement', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Type_statement', max_length=15, null=True)),
                ('data_statement', models.DateField(blank=True, db_column='Data_statement', null=True)),
            ],
            options={
                'db_table': 'Statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('num_vacation', models.IntegerField(db_column='Num_vacation', primary_key=True, serialize=False)),
                ('data_start_vacation', models.DateField(db_column='Data_start_vacation')),
                ('data_end_vacation', models.DateField(db_column='Data_end_vacation')),
                ('type_vacation', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Type_vacation', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Vacation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.IntegerField(db_column='ID_worker', primary_key=True, serialize=False)),
                ('fio_worker', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='FIO_worker', max_length=70)),
                ('post_name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Post_name', max_length=50, null=True)),
                ('data_birth', models.DateField(blank=True, db_column='Data_birth', null=True)),
                ('sex', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Sex', max_length=1, null=True)),
                ('allowance', models.FloatField(blank=True, db_column='Allowance', null=True)),
                ('stage', models.IntegerField(blank=True, db_column='Stage', null=True)),
                ('status', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Status', max_length=15, null=True)),
                ('work_reception_date', models.DateField(db_column='Work_reception_date')),
                ('data_termination', models.DateField(blank=True, db_column='Data_termination', null=True)),
            ],
            options={
                'db_table': 'Worker',
                'managed': False,
            },
        ),
    ]
